// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoH6YHs0oGNyQai9WT4aaX_tuggTUiXf4',
    appId: '1:531001121128:web:86e982cc8752488a2ededd',
    messagingSenderId: '531001121128',
    projectId: 'ges-b30b1',
    authDomain: 'ges-b30b1.firebaseapp.com',
    storageBucket: 'ges-b30b1.appspot.com',
    measurementId: 'G-FZYNKB05WS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9JitgqYDZVOgnPQAfdbqLEM6fwTYlYJI',
    appId: '1:531001121128:android:beefa9439ba5b20f2ededd',
    messagingSenderId: '531001121128',
    projectId: 'ges-b30b1',
    storageBucket: 'ges-b30b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKVuK_rjvmmvni7NJDGXAJevVsufq4j9k',
    appId: '1:531001121128:ios:7f1cccfa9400e21e2ededd',
    messagingSenderId: '531001121128',
    projectId: 'ges-b30b1',
    storageBucket: 'ges-b30b1.appspot.com',
    androidClientId: '531001121128-28qtu9ug1k2vbhohsvurffncc6edvtq7.apps.googleusercontent.com',
    iosClientId: '531001121128-mhrntrc00b2sdfqumrqrq456djg595qg.apps.googleusercontent.com',
    iosBundleId: 'com.example.ges',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKVuK_rjvmmvni7NJDGXAJevVsufq4j9k',
    appId: '1:531001121128:ios:7f1cccfa9400e21e2ededd',
    messagingSenderId: '531001121128',
    projectId: 'ges-b30b1',
    storageBucket: 'ges-b30b1.appspot.com',
    androidClientId: '531001121128-28qtu9ug1k2vbhohsvurffncc6edvtq7.apps.googleusercontent.com',
    iosClientId: '531001121128-mhrntrc00b2sdfqumrqrq456djg595qg.apps.googleusercontent.com',
    iosBundleId: 'com.example.ges',
  );
}
